config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :export_users
  resources :imports
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  CSV_ATTRIBUTES = %w(name email phone address).freeze
  attr_accessor :file

  class << self
    def import_file file
      spreadsheet = Roo::Spreadsheet.open file
      header = spreadsheet.row 1
      (2..spreadsheet.last_row).each do |i|
        row = [header, spreadsheet.row(i)].transpose.to_h
        create! row
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/export_users_controller.rb
class ExportUsersController < ApplicationController
  def index
    csv = ExportCsvService.new User.all, User::CSV_ATTRIBUTES
    respond_to do |format|
      format.csv { send_data csv.perform,
        filename: "users.csv" }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  def index
    @import = User.new
  end

  def create
    @import = User.import_file params[:file]
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/export_users_helper.rb
module ExportUsersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/home/index.html.erb
<h1>Đây là màn hình list user</h1>
<table>
  <thead>
    <th>name</th>
    <th>email</th>
    <th>phone</th>
    <th>address</th>
  </thead>
  <% @users.each do |u| %>
    <tbody>
      <td><%= u.name %></td>
      <td><%= u.email %></td>
      <td><%= u.phone %></td>
      <td><%= u.address %></td>
    </tbody>
  <% end %>
</table>
<%= link_to "Import", imports_path %>
<%= link_to "Ếch pọt", export_users_path(format: :csv) %>

app/views/imports/index.html.erb
<div>
  <h4>Import data</h4>
  <%= form_tag imports_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Csv</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>